[platformio]
src_dir = .
include_dir = .

[env:rp2354]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200

; Forcing ARM architecture compilation for the RP2350/RP2354 (Cortex-M33)
build_flags = 
    -D PICO_RP2350=1
