name: Build and Upload Firmwares

on:
  release:
    types: [published]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repository clonen
        uses: actions/checkout@v6 

      - name: Python für PlatformIO einrichten
        uses: actions/setup-python@v6 
        with:
          python-version: '3.10'

      - name: PlatformIO installieren
        run: pip install platformio

      - name: WROOM32D Firmware kompilieren
        run: pio run -d Firmware/WROOM32D -e esp32dev

      - name: RP2354A Firmware kompilieren
        run: pio run -d Firmware/RP2354A -e rp2354

      - name: Dateien für Release vorbereiten
        shell: bash
        run: |
          cp Firmware/WROOM32D/.pio/build/esp32dev/firmware.bin wroom.bin
          cp Firmware/RP2354A/.pio/build/rp2354/firmware.bin rp2354.bin

      - name: Assets an Release anhängen
        uses: softprops/action-gh-release@v2
        with:
          files: |
            wroom.bin
            rp2354.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
